### ISSUE TITLE
Package Installation Fails

### ISSUE THREAD

**Issue by ZellW** [hrbrmstr/tempestwx#1]
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\czwea\AppData\Local\Temp\RtmpW2ZLv6\remotes5078647d5f44\hrbrmstr-tempestwx-2ea56b0/DESCRIPTION' ...
─  preparing 'tempestwx':
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'tempestwx_0.1.0.tar.gz'
   
Installing package into ‘D:/Rpackages’
(as ‘lib’ is unspecified)
* installing *source* package 'tempestwx' ...
** using staged installation
** libs
g++  -std=gnu++11 -I"C:/R/R-42~1.0/include" -DNDEBUG  -I'D:/Rpackages/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
g++  -std=gnu++11 -I"C:/R/R-42~1.0/include" -DNDEBUG  -I'D:/Rpackages/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c code.cpp -o code.o
code.cpp:7:10: fatal error: netinet/in.h: No such file or directory
    7 | #include <netinet/in.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/R/R-42~1.0/etc/x64/Makeconf:259: code.o] Error 1
ERROR: compilation failed for package 'tempestwx'
* removing 'D:/Rpackages/tempestwx'

**Comment by hrbrmstr** [comment]
thx for the install report.

By the "`D:/…`" it appears you're on Windows. That's unfortunate.

I have no Windows environments, and it's just kind of sad Microsoft decided to not play nice with everyone else in the C world.

Truth be told, either of these:

- https://github.com/hrbrmstr/rust-weatherflow
- https://github.com/hrbrmstr/go-weatherflow

is a better solution for doing UDP datalogging from the Tempest wx devices in the long run (and are way easier to get running on Windows).

The Rust one powers the data logging behind https://rud.is/wx/
